### ISSUE TITLE
redis-namespace asks to use admistrative commands directly

### ISSUE THREAD

**Issue by Wolfer** [brpoplpush/brpoplpush-redis_script#19]
When Sidekiq configured use redis namespaces like this

```ruby
opts = {
  host:      APP_CONFIG[:redis_host].to_s,
  namespace: REDIS_NAMESPACE
}

Sidekiq.configure_server do |config|
  config.redis = opts
end

Sidekiq.configure_client do |config|
  config.redis = opts
end
```

Deprecated text appears at startup

```
Passing 'script' command to redis as is; administrative commands cannot be effectively namespaced and should be called on the redis connection directly; passthrough has been deprecated and will be removed in redis-namespace 2.0 (at /usr/local/rvm/gems/ruby-2.6.3/gems/brpoplpush-redis_script-0.1.1/lib/brpoplpush/redis_script/script.rb:69:in `load')
Passing 'script' command to redis as is; administrative commands cannot be effectively namespaced and should be called on the redis connection directly; passthrough has been deprecated and will be removed in redis-namespace 2.0 (at /usr/local/rvm/gems/ruby-2.6.3/gems/brpoplpush-redis_script-0.1.1/lib/brpoplpush/redis_script/script.rb:69:in `load')

````

**Comment by Wolfer** [comment]
https://github.com/resque/redis-namespace#administrative-commands

**Comment by mhenrixon** [comment]
For whatever reason I didn't see this. Thanks for the PR, I will go ahead and close this now :)
